### ISSUE TITLE
New create version incompatible with the mod.

### ISSUE THREAD

**Issue by masteri212** [dryas-octopetala/ae2_create_evecompat_data#2]
Create fabric got an update and the mod dosen't launch with it.
<img width="477" alt="Képernyőkép 2024-11-19 055923" src="https://github.com/user-attachments/assets/fcea9027-81f6-4821-a5b6-0268a55b390a" />

**Comment by dryas-octopetala** [comment]
Thanks for letting me know. Didn't realize I put a wrongful dependency in it. I'll fix it in a few minutes.

**Comment by dryas-octopetala** [comment]
Nvm, something is not quite right and nothing I do stops that from happening. I'm going to un-list the mod until I'm done with the next update amidst all of the holiday chaos. 

Many apologies.
